title: "DISEÑO DE UN SISTEMA DE ILUMINACIÓN AUTOMÁTICA CON ARDUINO"
description: "Teoría, práctica y proyecto"
theme: minima

url: "https://joapino08.github.io"
baseurl: "/situacion-aprendizaje"

search_enabled: true
nav_enabled: true
